name: Hello World Workflow

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World!"