name: Hello World Workflow

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch

jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World!"
  date_job:
    runs-on: ubuntu-latest
    steps:
      - name: Now it is
        run: date  
  directory:
    runs-on: ubuntu-latest
    steps:
      - name: Directory content
        run: ls -l
