name: Hello World Workflow

on:
  push:
    branches:
      - main 
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World!"
  date_job:
    runs-on: ubuntu-latest
    steps:
      - name: Now it is
        run: date  
  directory:
    runs-on: ubuntu-latest
    steps:
      - name: Directory content
        run: ls -l
